### ISSUE TITLE
Dependencies Out Of Date - Issues On npm install

### ISSUE THREAD

**Issue by k1ngdr3w** [alexbrombal/selenium-sauce#4]
Please update dependencies:

"sauce-connect-launcher": "^0.12.0",
"saucelabs": "^0.1.1",
"selenium-standalone": "4.5.3",
"webdriverio": "^3.1.0"

**Comment by alexbrombal** [comment]
Hi k1ngdr3w,

I have updated the dependencies, and also made a few changes to the structure of the configuration object. Everything in the README file has been updated to reflect this so you should be able to make the necessary changes.

All the `npm test`s seem to be passing and the example located in the `examples` folder also works.

Please let me know if you have any issues!

**Comment by alexbrombal** [comment]
Sorry, I won't close it yet, so you have a chance to verify it...

**Comment by k1ngdr3w** [comment]
https://github.com/alexbrombal/selenium-sauce/commit/931690dbbd8592dd0c729ada1fb808253bff1b90 looks good! Close it!
