### ISSUE TITLE
Broken Version in npm

### ISSUE THREAD

**Issue by DrLongGhost** [alexbrombal/selenium-sauce#5]
The current version in npm (0.3.4) does not seem to work for me.

I downloaded the latest code from github and ran the examples and they worked fine. After comparing the files, I see that there are changes from 10 months ago that were never pushed to npm. Applying those changes to the version from npm makes "selenium-sauce" work as expected.

Would you please be able to push a version 0.3.5 with those changes so I won't have to patch them in?

Also (and far less important), I'm seeing this output when I run the examples:

  Selenium:
    chrome: title
      ✓ should have the correct value (178ms)
    firefox: title
      ✓ should have the correct value (174ms)
    1) "after all" hook

  2 passing (36s)
  1 failing

  1) Selenium: "after all" hook:
     TypeError: Cannot read property 'state' of undefined
      at Context.<anonymous> (test.mocha.js:44:42)

**Comment by brombal** [comment]
Sure thing, I will look into it and give you an update soon.

**Comment by alexbrombal** [comment]
I've pushed an update that should fix this (my local unit tests and CI unit tests on codeship ran). All the dependencies are up to date, too. Can you let me know if that fixes it?

**Comment by DrLongGhost** [comment]
That fixed the issue for me. Thanks very much for your help!
